#!/usr/bin/env bash
# Seed a libFuzzer target from repository fixtures and committed seed inputs.
#
# `decode_drc` receives every `*.drc` fixture. The glTF targets receive every
# `*.gltf` and `*.glb` fixture plus target-specific files under `fuzz/seeds/`.
#
# Usage: fuzz/seed_corpus.sh [target_name]
set -euo pipefail

target="${1:-decode_drc}"
fuzz_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
repo_root="$(cd "$fuzz_dir/.." && pwd)"
testdata="$repo_root/testdata"
corpus="$fuzz_dir/corpus/$target"

if [ ! -d "$testdata" ]; then
    echo "testdata directory not found at $testdata" >&2
    exit 1
fi

mkdir -p "$corpus"

case "$target" in
  decode_drc)
    find_args=( -name '*.drc' )
    ;;
  compress_gltf|draco_gltf_import)
    find_args=( \( -name '*.gltf' -o -name '*.glb' \) )
    ;;
  fbx_read_scene|fbx_roundtrip)
    # No .fbx fixtures are committed under testdata/; these targets are seeded
    # entirely from fuzz/seeds/<target>/, which is generated by
    # `cargo run -p draco-io --example fbx_make_seeds`.
    find_args=( -name '*.fbx' )
    ;;
  *)
    echo "Unknown fuzz target '$target'" >&2
    exit 1
    ;;
esac

count=0
while IFS= read -r -d '' file; do
    relative="${file#"$testdata"/}"
    flat_name="${relative//\//__}"
    cp -f "$file" "$corpus/fixture__$flat_name"
    count=$((count + 1))
done < <(find "$testdata" -type f "${find_args[@]}" -print0)

seed_dir="$fuzz_dir/seeds/$target"
if [ -d "$seed_dir" ]; then
  while IFS= read -r -d '' file; do
    cp -f "$file" "$corpus/seed__$(basename "$file")"
    count=$((count + 1))
  done < <(find "$seed_dir" -maxdepth 1 -type f -print0)
fi

echo "Seeded $count fixture(s) into $corpus"
