<#
.SYNOPSIS
  Seed a libFuzzer target from repository fixtures and committed seed inputs.

.DESCRIPTION
  `decode_drc` receives every `*.drc` fixture. The glTF targets receive every
  `*.gltf` and `*.glb` fixture plus target-specific files under `fuzz/seeds/`.
  Path-derived names avoid collisions. The corpus directory is git-ignored and
  reconstructed deterministically.

.EXAMPLE
  pwsh fuzz/seed_corpus.ps1
#>
[CmdletBinding()]
param(
    [string]$Target = 'decode_drc'
)

$ErrorActionPreference = 'Stop'

$fuzzDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$repoRoot = Split-Path -Parent $fuzzDir
$testdata = Join-Path $repoRoot 'testdata'
$corpus = Join-Path $fuzzDir "corpus/$Target"

if (-not (Test-Path $testdata)) {
    throw "testdata directory not found at $testdata"
}

New-Item -ItemType Directory -Force -Path $corpus | Out-Null

$patterns = switch ($Target) {
    'decode_drc' { @('*.drc') }
    'compress_gltf' { @('*.gltf', '*.glb') }
    'draco_gltf_import' { @('*.gltf', '*.glb') }
    # No .fbx fixtures live under testdata/; these are seeded from
    # fuzz/seeds/<target>/, generated by the fbx_make_seeds example.
    'fbx_read_scene' { @('*.fbx') }
    'fbx_roundtrip' { @('*.fbx') }
    default { throw "Unknown fuzz target '$Target'" }
}

$fixtures = foreach ($pattern in $patterns) {
    Get-ChildItem -Path $testdata -Recurse -Filter $pattern -File
}

$count = 0
$fixtures | Sort-Object FullName -Unique | ForEach-Object {
    $relative = $_.FullName.Substring($testdata.Length).TrimStart('\', '/')
    $flatName = "fixture__" + ($relative -replace '[\\/]', '__')
    Copy-Item -LiteralPath $_.FullName -Destination (Join-Path $corpus $flatName) -Force
    $count++
}

$seedDir = Join-Path $fuzzDir "seeds/$Target"
if (Test-Path $seedDir) {
    Get-ChildItem -Path $seedDir -File | ForEach-Object {
        Copy-Item -LiteralPath $_.FullName -Destination (Join-Path $corpus "seed__$($_.Name)") -Force
        $count++
    }
}

Write-Host "Seeded $count fixture(s) into $corpus"
