/// Decode performance comparison using C++-encoded .drc files.
///
/// This is the fairest possible benchmark: both decoders receive exactly the
/// same bytes produced by the C++ reference encoder, so there is no question
/// about encoder bias.
mod common;

use std::path::PathBuf;
use std::time::{Duration, Instant};

use draco_core::decoder_buffer::DecoderBuffer;
use draco_core::mesh::Mesh;
use draco_core::mesh_decoder::MeshDecoder;
use draco_cpp_test_bridge;

fn testdata_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .unwrap()
        .parent()
        .unwrap()
        .join("testdata")
}

/// Decode `data` with the Rust decoder `iters` times.
/// Returns `(avg_us, num_points, num_faces)` or `None` on failure.
fn bench_rust_decode(data: &[u8], iters: u32) -> Option<(f64, usize, usize)> {
    let mut total = Duration::ZERO;
    let mut pts = 0;
    let mut faces = 0;
    for _ in 0..iters {
        let mut buf = DecoderBuffer::new(data);
        let mut mesh = Mesh::new();
        let mut dec = MeshDecoder::new();
        let start = Instant::now();
        dec.decode(&mut buf, &mut mesh).ok()?;
        total += start.elapsed();
        pts = mesh.num_points();
        faces = mesh.num_faces();
    }
    Some((
        total.as_secs_f64() * 1_000_000.0 / f64::from(iters),
        pts,
        faces,
    ))
}

/// Decode `data` with the C++ decoder `iters` times.
/// Returns `(avg_us, num_points, num_faces)` or `None` when the C++ test bridge is unavailable.
fn bench_cpp_decode(data: &[u8], iters: u32) -> Option<(f64, usize, usize)> {
    let r = draco_cpp_test_bridge::profile_cpp_decode(data, iters)?;
    Some((
        r.decode_time_us as f64,
        r.num_points as usize,
        r.num_faces as usize,
    ))
}

struct FileCase {
    label: &'static str,
    path: Vec<&'static str>, // relative path components from testdata/
    iters: u32,
}

#[test]
fn bench_decode_real_files() {
    common::disable_noisy_debug_env();

    if !draco_cpp_test_bridge::is_available() {
        eprintln!("SKIPPING: C++ test bridge not available");
        return;
    }

    let base = testdata_dir();

    // Files generated by the C++ encoder (reference_cpp/) — one per speed.
    // Also include some real-world .drc files.
    let reference_files: Vec<FileCase> = (0..=10)
        .map(|s| FileCase {
            label: Box::leak(format!("sphere speed {}", s).into_boxed_str()),
            path: vec![
                "reference_cpp",
                Box::leak(format!("cpp_encoded_sphere_speed_{}.drc", s).into_boxed_str()),
            ],
            iters: 200,
        })
        .chain((0..=10).map(|s| FileCase {
            label: Box::leak(format!("cube   speed {}", s).into_boxed_str()),
            path: vec![
                "reference_cpp",
                Box::leak(format!("cpp_encoded_cube_speed_{}.drc", s).into_boxed_str()),
            ],
            iters: 200,
        }))
        .collect();

    let real_files: &[FileCase] = &[
        FileCase {
            label: "bunny (cpp)",
            path: vec!["bunny_cpp.drc"],
            iters: 50,
        },
        FileCase {
            label: "bunny (cpp standard)",
            path: vec!["bunny_cpp_standard.drc"],
            iters: 50,
        },
        // testdata/cube_att.drc is a bitstream v1.1 mesh below the current
        // Draco 1.0.0+ compatibility floor. C++ expands its split attribute
        // connectivity to 24 logical mesh points, while the Rust decoder
        // currently recovers only the 8 unique position points, so it is not a
        // valid apples-to-apples decode performance case.
        FileCase {
            label: "annulus (edgbrk)",
            path: vec!["annulus_eb.drc"],
            iters: 200,
        },
        FileCase {
            label: "car",
            path: vec!["car.drc"],
            iters: 50,
        },
    ];

    println!();
    println!("╔══════════════════════════════════════════════════════════════════════════════╗");
    println!("║   DECODE PERFORMANCE — C++ encoded files decoded by C++ vs Rust            ║");
    println!("╚══════════════════════════════════════════════════════════════════════════════╝");
    println!("(Both decoders receive identical bytes produced by the C++ reference encoder)");
    println!();

    // ── Reference files (synthetic, all speeds) ──────────────────────────────
    println!("── Synthetic reference files (C++ encoder output, speeds 0–10) ─────────────");
    println!(
        "┌──────────────────────┬────────┬────────┬────────┬───────────┬───────────┬─────────┬─────────┐"
    );
    println!(
        "│ File                 │ Bytes  │ Points │ Faces  │ C++ (µs)  │ Rust (µs) │ Speedup │ Winner  │"
    );
    println!(
        "├──────────────────────┼────────┼────────┼────────┼───────────┼───────────┼─────────┼─────────┤"
    );

    for case in &reference_files {
        let mut p = base.clone();
        for seg in &case.path {
            p = p.join(seg);
        }
        let data = match std::fs::read(&p) {
            Ok(d) => d,
            Err(_) => {
                println!(
                    "│ {:<20} │  n/a   │   n/a  │   n/a  │   MISSING │   MISSING │    -    │    -    │",
                    case.label
                );
                continue;
            }
        };

        let rust = bench_rust_decode(&data, case.iters);
        let cpp = bench_cpp_decode(&data, case.iters);

        match (rust, cpp) {
            (Some((r_us, r_pts, r_faces)), Some((c_us, c_pts, c_faces))) => {
                let speedup = c_us / r_us;
                let winner = if speedup >= 1.0 { "Rust" } else { "C++" };
                let ok = if r_pts == c_pts && r_faces == c_faces {
                    "✓"
                } else {
                    "✗"
                };
                println!(
                    "│ {:<20} │{:>7} │{:>7} │{:>7} │ {:>9.1} │ {:>9.1} │ {:>6.2}x{} │ {:>7} │",
                    case.label,
                    data.len(),
                    r_pts,
                    r_faces,
                    c_us,
                    r_us,
                    speedup,
                    ok,
                    winner
                );
            }
            (None, _) => println!(
                "│ {:<20} │{:>7} │   n/a  │   n/a  │ {:>9.1} │ RUST FAIL │    -    │    -    │",
                case.label,
                data.len(),
                cpp.map(|c| c.0).unwrap_or(0.0)
            ),
            (_, None) => println!(
                "│ {:<20} │{:>7} │   n/a  │   n/a  │  BRIDGE FAIL │ {:>9.1} │    -    │    -    │",
                case.label,
                data.len(),
                rust.map(|r| r.0).unwrap_or(0.0)
            ),
        }
    }

    println!(
        "└──────────────────────┴────────┴────────┴────────┴───────────┴───────────┴─────────┴─────────┘"
    );

    // ── Real-world files ──────────────────────────────────────────────────────
    println!();
    println!("── Real-world .drc files ─────────────────────────────────────────────────────");
    println!(
        "┌──────────────────────┬────────┬────────┬────────┬───────────┬───────────┬─────────┬─────────┐"
    );
    println!(
        "│ File                 │ Bytes  │ Points │ Faces  │ C++ (µs)  │ Rust (µs) │ Speedup │ Winner  │"
    );
    println!(
        "├──────────────────────┼────────┼────────┼────────┼───────────┼───────────┼─────────┼─────────┤"
    );

    for case in real_files {
        let mut p = base.clone();
        for seg in &case.path {
            p = p.join(seg);
        }
        let data = match std::fs::read(&p) {
            Ok(d) => d,
            Err(_) => {
                println!(
                    "│ {:<20} │  n/a   │   n/a  │   n/a  │   MISSING │   MISSING │    -    │    -    │",
                    case.label
                );
                continue;
            }
        };

        let rust = bench_rust_decode(&data, case.iters);
        let cpp = bench_cpp_decode(&data, case.iters);

        match (rust, cpp) {
            (Some((r_us, r_pts, r_faces)), Some((c_us, c_pts, c_faces))) => {
                let speedup = c_us / r_us;
                let winner = if speedup >= 1.0 { "Rust" } else { "C++" };
                let ok = if r_pts == c_pts && r_faces == c_faces {
                    "✓"
                } else {
                    "✗"
                };
                println!(
                    "│ {:<20} │{:>7} │{:>7} │{:>7} │ {:>9.1} │ {:>9.1} │ {:>6.2}x{} │ {:>7} │",
                    case.label,
                    data.len(),
                    r_pts,
                    r_faces,
                    c_us,
                    r_us,
                    speedup,
                    ok,
                    winner
                );
            }
            (None, _) => println!(
                "│ {:<20} │{:>7} │   n/a  │   n/a  │ {:>9.1} │ RUST FAIL │    -    │    -    │",
                case.label,
                data.len(),
                cpp.map(|c| c.0).unwrap_or(0.0)
            ),
            (_, None) => println!(
                "│ {:<20} │{:>7} │   n/a  │   n/a  │  BRIDGE FAIL │ {:>9.1} │    -    │    -    │",
                case.label,
                data.len(),
                rust.map(|r| r.0).unwrap_or(0.0)
            ),
        }
    }

    println!(
        "└──────────────────────┴────────┴────────┴────────┴───────────┴───────────┴─────────┴─────────┘"
    );
    println!();
    println!("Notes:");
    println!("  • Speedup > 1.0x means Rust is faster");
    println!("  • ✓ = decoded point/face counts match between Rust and C++");
    println!("  • Iterations: reference files = 200, real-world files = 50");
    println!("  • C++ built with /O2 (Release), Rust with opt-level=3 + thin LTO");
    println!();
}
