//! The fuzzing seeds are real files, and this is what says so.
//!
//! A seed that does not parse is worse than no seed: the corpus looks stocked
//! and the engine starts from nothing, which is exactly the failure the
//! campaign before them had for a different reason. They are generated by
//! `cargo run -p draco-texture --example ktx2_make_seeds -- fuzz/seeds` and
//! committed, so this checks in what was committed rather than regenerating.

use std::path::{Path, PathBuf};

use draco_texture::ktx2::{Ktx2, Ktx2Format, Supercompression};
use draco_texture::transcode::{Target, Transcoder};

/// Every seed, with what it should turn out to be.
const SEEDS: [(&str, u32, Supercompression, bool); 6] = [
    ("uastc_8.ktx2", 8, Supercompression::None, false),
    ("uastc_64.ktx2", 64, Supercompression::None, false),
    ("etc1s_8.ktx2", 8, Supercompression::BasisLz, true),
    ("etc1s_64.ktx2", 64, Supercompression::BasisLz, true),
    ("etc1s_alpha_64.ktx2", 64, Supercompression::BasisLz, true),
    ("etc1s_facecap_64.ktx2", 64, Supercompression::BasisLz, true),
];

fn seed(name: &str) -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("../../fuzz/seeds/ktx2_transcode")
        .join(name)
}

#[test]
fn every_seed_parses_and_decodes() {
    for (name, size, supercompression, is_etc1s) in SEEDS {
        let bytes = std::fs::read(seed(name))
            .unwrap_or_else(|error| panic!("{name} is missing; regenerate the seeds: {error}"));
        let file = Ktx2::parse(&bytes).unwrap_or_else(|error| panic!("parsing {name}: {error}"));

        assert_eq!((file.width(), file.height()), (size, size), "{name} size");
        assert_eq!(file.level_count(), 1, "{name} should hold one level");
        assert_eq!(
            file.supercompression(),
            supercompression,
            "{name} supercompression"
        );
        assert_eq!(
            matches!(file.format(), Ktx2Format::Etc1s { .. }),
            is_etc1s,
            "{name} codec"
        );

        // Reaching the codec is the whole point of a seed: a file the reader
        // accepts and then fails to decode would leave the transcoder as
        // unexplored as no seed at all.
        let transcoder = Transcoder::new(&file)
            .unwrap_or_else(|error| panic!("reading {name}'s codebooks: {error}"));
        let blocks = (size.div_ceil(4) as usize) * (size.div_ceil(4) as usize);
        for (target, per_block) in [
            (Target::Rgba8, 0),
            (Target::Bc1, 8),
            (Target::Bc3, 16),
            (Target::Etc1, 8),
            (Target::Etc2, 16),
            (Target::Astc, 16),
            (Target::Bc7, 16),
        ] {
            let decoded = match transcoder.decode(&file, 0, 0, 0, target) {
                Ok(decoded) => decoded,
                // ETC1S has no BC7 target and UASTC no BC1 or BC3, and which
                // is which is the codec's business rather than this test's.
                Err(_) => continue,
            };
            let expected = if per_block == 0 {
                (size * size * 4) as usize
            } else {
                blocks * per_block
            };
            assert_eq!(decoded.bytes.len(), expected, "{name} into {target:?}");
        }
    }
}

#[test]
fn the_seeds_are_small_enough_to_fuzz_with() {
    // The reason they exist. A seed the size of a real texture costs
    // milliseconds an execution, and a mutation engine given one explores
    // nothing: the first campaign over the fixtures managed four executions a
    // second. Sixteen kilobytes is generous for a container with codebooks in
    // it and still two orders of magnitude below a 1024-square fixture.
    for (name, ..) in SEEDS {
        let length = std::fs::metadata(seed(name))
            .map(|meta| meta.len())
            .unwrap();
        assert!(
            length < 20 * 1024,
            "{name} is {length} bytes, which is too large to seed a campaign with"
        );
    }
}
