//! The FBX fuzzing seeds are the files the generator says they are.
//!
//! A seed that does nothing is worse than no seed: the corpus looks stocked
//! while the engine starts from nothing, and the ASCII parser had exactly that
//! problem for the opposite reason -- every seed began with the binary magic,
//! so mutation had to synthesize `; FBX` by chance to reach the parser at all.
//! These are generated by
//! `cargo run -p draco-io --example fbx_make_seeds -- fuzz/seeds` and
//! committed, so this checks in what was committed rather than regenerating.
//!
//! The malformed seeds must *fail*, and each for its own reason. A malformed
//! seed that quietly parses is covering nothing, which is the same defect one
//! step further along.

use std::path::{Path, PathBuf};

use draco_io::fbx_ascii::is_ascii_fbx;
use draco_io::{FbxDecodeLimits, FbxReadOptions, FbxScene};

/// What each seed is, under the limits the fuzz target uses.
///
/// The lenient/strict pair is the assertion, not just "does it parse": a seed
/// that both modes reject stops at the first byte, while one lenient mode
/// tolerates and strict mode refuses is a seed that reached the recovery path
/// and kept going. Both are useful, and they are not the same seed.
///
/// A `bad_`/`unterminated` seed that strict mode accepts has stopped testing
/// what it was written for.
const SEEDS: [(&str, bool, bool, bool); 17] = [
    // name, is ASCII, lenient parses, strict parses
    ("valid_triangle.fbx", false, true, true),
    // Structurally fine, but empty: strict mode wants scene content.
    ("empty_7400.fbx", false, true, false),
    ("empty_7500.fbx", false, true, false),
    ("empty_big_endian_7500.fbx", false, true, false),
    // An end offset before the record's own header cannot be resynchronized
    // from, so both modes stop.
    ("bad_end_offset_backward.fbx", false, false, false),
    // These two are tolerated and resynchronized past, which is what makes
    // them worth seeding: they reach the recovery path rather than the first
    // rejection.
    ("bad_end_offset_past_eof.fbx", false, true, false),
    ("bad_property_list_len.fbx", false, true, false),
    ("bad_array_element_count.fbx", false, false, false),
    ("bad_zlib_bomb.fbx", false, false, false),
    ("ascii_valid.fbx", true, true, true),
    ("ascii_material_slots.fbx", true, true, true),
    ("ascii_material_layer_no_slots.fbx", true, true, true),
    ("ascii_blend_shape.fbx", true, true, true),
    // 24 levels against the fuzzing limit of 16.
    ("ascii_deep_nesting.fbx", true, false, false),
    ("ascii_huge_array_len.fbx", true, false, false),
    ("ascii_unterminated_string.fbx", true, false, false),
    ("ascii_unterminated_block.fbx", true, false, false),
];

fn seed(name: &str) -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("../../fuzz/seeds/fbx_read_scene")
        .join(name)
}

#[test]
fn every_seed_is_what_the_generator_says_it_is() {
    for (name, is_ascii, lenient_parses, strict_parses) in SEEDS {
        let bytes = std::fs::read(seed(name))
            .unwrap_or_else(|error| panic!("{name} is missing; regenerate the seeds: {error}"));

        // Routing first: an ASCII seed the detector does not recognise never
        // reaches the parser it was written for, and would look like a
        // perfectly good seed from the corpus listing.
        assert_eq!(is_ascii_fbx(&bytes), is_ascii, "{name}: container routing");

        let limits = FbxDecodeLimits::fuzzing();
        let lenient = FbxScene::from_bytes_with_options(
            &bytes,
            FbxReadOptions::default().with_limits(limits),
        );
        let strict =
            FbxScene::from_bytes_with_options(&bytes, FbxReadOptions::strict().with_limits(limits));

        assert_eq!(
            lenient.is_ok(),
            lenient_parses,
            "{name}, lenient: {}",
            describe(&lenient, lenient_parses)
        );
        assert_eq!(
            strict.is_ok(),
            strict_parses,
            "{name}, strict: {}",
            describe(&strict, strict_parses)
        );
    }
}

fn describe(result: &std::io::Result<FbxScene>, expected: bool) -> String {
    match result {
        Ok(_) => format!("parsed, expected {expected}"),
        Err(error) => format!("failed, expected {expected}: {error}"),
    }
}

/// The valid ASCII seed carries geometry, not just a parseable document.
///
/// Structure alone would let the seed stop at the node tree; the point of a
/// valid seed is that mutation starts from something that reached the scene
/// builder.
#[test]
fn the_valid_ascii_seed_carries_a_mesh() {
    let bytes = std::fs::read(seed("ascii_valid.fbx")).expect("ascii_valid.fbx");
    let scene = FbxScene::from_bytes_with_options(
        &bytes,
        FbxReadOptions::default().with_limits(FbxDecodeLimits::fuzzing()),
    )
    .expect("ascii_valid.fbx should parse");
    let instance = scene
        .root_nodes
        .iter()
        .flat_map(|node| node.mesh_instances.iter())
        .next()
        .expect("the seed declares one Geometry node");
    assert_eq!(instance.mesh.num_points(), 3, "three vertices");
    assert_eq!(instance.mesh.num_faces(), 1, "one triangle");
}

/// The two seeds written for the round-trip target reach what they were
/// written for.
///
/// Parsing is not the bar here. These exist because the round-trip target can
/// only check the mapping a scene actually carries, and every other input in
/// the corpus carries neither a material layer nor a deformer -- so a seed
/// that parsed into a plain mesh would leave that mapping fuzzed over nothing
/// while the corpus listing showed it covered.
#[test]
fn the_round_trip_seeds_carry_the_mappings_they_were_written_for() {
    let read = |name: &str| {
        let bytes = std::fs::read(seed(name)).unwrap_or_else(|error| panic!("{name}: {error}"));
        FbxScene::from_bytes_with_options(
            &bytes,
            FbxReadOptions::default().with_limits(FbxDecodeLimits::fuzzing()),
        )
        .unwrap_or_else(|error| panic!("{name} should parse: {error}"))
    };

    let slots = read("ascii_material_slots.fbx");
    assert_eq!(slots.materials.len(), 3, "three materials");
    let mesh = &slots.root_nodes[0].mesh_instances[0];
    // Slots are a, b, a, c: the layer sends one face to the fourth slot and
    // one to the third, which are materials c and a. Reading the repeated
    // connection as one slot answers [0, 2] here.
    assert_eq!(mesh.material_indices, vec![2, 0], "per-face materials");

    let morphs = read("ascii_blend_shape.fbx");
    let mesh = &morphs.root_nodes[0].mesh_instances[0];
    assert_eq!(mesh.morph_targets.len(), 1, "one blend-shape target");
    assert_eq!(
        mesh.morph_targets[0].control_point_indices,
        vec![0, 2],
        "the deltas the shape names"
    );
}

/// A material layer on a Model with no material slots addresses nothing.
///
/// The layer's values are slot numbers, and a Model that has no material
/// connected to it has no slot for any of them. They used to be read through
/// unchanged, as if they were scene material indices, and the writer then
/// resolved them against the material table: `3, 2` was written as one
/// connected material and came back as `2, 2`. The round-trip fuzz target
/// found it inside its first two-minute run with a dictionary.
///
/// The one case the values are kept is a document with no `Material` objects
/// at all, which Revit exports do. There is nothing to resolve against and
/// nothing the writer could confuse them with, and dropping them would erase
/// the face grouping the layer encodes.
#[test]
#[cfg(feature = "fbx-writer")]
fn a_material_layer_without_slots_reads_as_no_materials_and_round_trips() {
    let lenient = FbxReadOptions::default().with_limits(FbxDecodeLimits::fuzzing());
    let strict = FbxReadOptions::strict().with_limits(FbxDecodeLimits::permissive());
    let indices = |scene: &FbxScene| {
        scene.root_nodes[0].mesh_instances[0]
            .material_indices
            .clone()
    };

    let bytes = std::fs::read(seed("ascii_material_layer_no_slots.fbx"))
        .expect("ascii_material_layer_no_slots.fbx");
    let scene =
        FbxScene::from_bytes_with_options(&bytes, lenient.clone()).expect("the seed should parse");
    assert_eq!(scene.materials.len(), 3, "the document has materials");
    assert_eq!(
        indices(&scene),
        Vec::<i32>::new(),
        "no slot to resolve against"
    );
    for written in [scene.to_bytes(), scene.to_ascii_bytes()] {
        let written = written.expect("the writer represents this scene");
        let reread = FbxScene::from_bytes_with_options(&written, strict.clone())
            .expect("the writer's output is strict-readable");
        assert_eq!(
            indices(&reread),
            indices(&scene),
            "unchanged across a rewrite"
        );
    }

    // The same layer in a document with no materials at all: kept as written.
    // Cut the three Material objects out of the seed, closing `Objects` where
    // they stood.
    let text = String::from_utf8(bytes).expect("the seed is ASCII");
    let start = text
        .find("    Material: 300")
        .expect("the seed's first material");
    let end = text.find("Connections:").expect("the seed's connections");
    let without_materials = format!("{}}}\n{}", &text[..start], &text[end..]);
    let scene = FbxScene::from_bytes_with_options(without_materials.as_bytes(), lenient)
        .expect("the document without materials should parse");
    assert_eq!(scene.materials.len(), 0, "no materials in the document");
    assert_eq!(indices(&scene), vec![3, 2], "kept as written");
    let written = scene.to_bytes().expect("the writer represents this scene");
    let reread = FbxScene::from_bytes_with_options(&written, strict)
        .expect("the writer's output is strict-readable");
    assert_eq!(indices(&reread), vec![3, 2], "unchanged across a rewrite");
}

/// The one seed that comes from our own writer is still what the writer emits.
///
/// It was not: the committed bytes predate the axis-system change in
/// `fbx: read the declared axis system, and declare the one that is written`,
/// so the corpus carried a document this crate had stopped producing. Nothing
/// failed -- a stale seed still parses, which is exactly why staleness needs
/// its own check rather than riding on the parse assertions above.
#[test]
#[cfg(feature = "fbx-writer")]
fn the_generated_seed_matches_what_the_writer_emits_today() {
    use draco_core::draco_types::DataType;
    use draco_core::geometry_attribute::{GeometryAttributeType, PointAttribute};
    use draco_core::geometry_indices::{FaceIndex, PointIndex};
    use draco_core::mesh::Mesh;
    use draco_io::traits::Writer;
    use draco_io::FbxWriter;

    // The same triangle `fbx_make_seeds` builds.
    let mut mesh = Mesh::new();
    mesh.set_num_points(3);
    let mut position = PointAttribute::new();
    position.init(
        GeometryAttributeType::Position,
        3,
        DataType::Float32,
        false,
        3,
    );
    for (index, point) in [[0.0f32, 0.0, 0.0], [1.0, 0.0, 0.0], [0.0, 1.0, 0.0]]
        .iter()
        .enumerate()
    {
        let bytes: Vec<u8> = point.iter().flat_map(|v| v.to_le_bytes()).collect();
        position.buffer_mut().write(index * 12, &bytes);
    }
    mesh.add_attribute(position);
    mesh.set_num_faces(1);
    mesh.set_face(FaceIndex(0), [PointIndex(0), PointIndex(1), PointIndex(2)]);

    let mut writer = FbxWriter::new();
    writer.add_mesh(&mesh, Some("seed")).expect("add_mesh");
    let fresh = writer.write_to_vec().expect("write_to_vec");
    let committed = std::fs::read(seed("valid_triangle.fbx")).expect("valid_triangle.fbx");

    assert_eq!(
        committed, fresh,
        "valid_triangle.fbx is stale; regenerate with \
         `cargo run -p draco-io --example fbx_make_seeds -- fuzz/seeds`"
    );
}
